<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <InternalsVisibleTo Include="HkdfGuard.DataEncryptionKey.Test" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HkdfGuard.Abstractions\HkdfGuard.Abstractions.csproj" />
      <ProjectReference Include="..\HkdfGuard.Diagnostics\HkdfGuard.Diagnostics.csproj" />
    </ItemGroup>

</Project>
